# Cell 1 - Markdown
"""
# 01 Data Cleaning

## Student Performance Prediction Using Machine Learning

This notebook prepares the raw student performance dataset for machine learning.

Main tasks:
- Load the raw dataset
- Inspect dataset structure
- Handle missing values
- Check duplicates
- Correct invalid values
- Create Pass/Fail target
- Validate the cleaned dataset
- Save the cleaned dataset and cleaning summary
"""

In [4]:
# Cell 2 - Import Libraries

import pandas as pd
import numpy as np
from pathlib import Path

In [5]:
# Cell 3 - Define Paths

PROJECT_ROOT = Path("..")

RAW_DATA_PATH = PROJECT_ROOT / "data" / "raw" / "StudentPerformanceFactors.csv"
PROCESSED_DATA_PATH = PROJECT_ROOT / "data" / "processed" / "StudentPerformanceFactors_cleaned.csv"

TABLES_DIR = PROJECT_ROOT / "outputs" / "tables"
TABLES_DIR.mkdir(parents=True, exist_ok=True)

print("Raw data path:", RAW_DATA_PATH)
print("Processed data path:", PROCESSED_DATA_PATH)
print("Tables directory:", TABLES_DIR)

Raw data path: ..\data\raw\StudentPerformanceFactors.csv
Processed data path: ..\data\processed\StudentPerformanceFactors_cleaned.csv
Tables directory: ..\outputs\tables

In [6]:
# Cell 4 - Load Dataset

df = pd.read_csv(RAW_DATA_PATH)

df.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70

In [7]:
# Cell 5 - Dataset Overview

print("Dataset Shape:")
print(f"Rows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")

print("\nColumn Names:")
for col in df.columns:
    print("-", col)

Dataset Shape:
Rows: 6607
Columns: 20

Column Names:
- Hours_Studied
- Attendance
- Parental_Involvement
- Access_to_Resources
- Extracurricular_Activities
- Sleep_Hours
- Previous_Scores
- Motivation_Level
- Internet_Access
- Tutoring_Sessions
- Family_Income
- Teacher_Quality
- School_Type
- Peer_Influence
- Physical_Activity
- Learning_Disabilities
- Parental_Education_Level
- Distance_from_Home
- Gender
- Exam_Score

In [8]:
# Cell 6 - Data Information

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               6607 non-null   int64
 1   Attendance                  6607 non-null   int64
 2   Parental_Involvement        6607 non-null   object
 3   Access_to_Resources         6607 non-null   object
 4   Extracurricular_Activities  6607 non-null   object
 5   Sleep_Hours                 6607 non-null   int64
 6   Previous_Scores             6607 non-null   int64
 7   Motivation_Level            6607 non-null   object
 8   Internet_Access             6607 non-null   object
 9   Tutoring_Sessions           6607 non-null   int64
 10  Family_Income               6607 non-null   object
 11  Teacher_Quality             6529 non-null   object
 12  School_Type                 6607 non-null   object
 13  Peer_Influence              6607 non-null   object
 14  Physical_Activity           6607 non-null   int64
 15  Learning_Disabilities       6607 non-null   object
 16  Parental_Education_Level    6517 non-null   object
 17  Distance_from_Home          6540 non-null   object
 18  Gender                      6607 non-null   object
 19  Exam_Score                  6607 non-null   int64
dtypes: int64(7), object(13)
memory usage: 1.0+ MB

In [9]:
# Cell 7 - Check Missing Values

missing_values = df.isnull().sum()
missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_summary = pd.DataFrame({
    "Missing Values": missing_values,
    "Missing Percentage (%)": missing_percentage.round(2)
})

missing_summary[missing_summary["Missing Values"] > 0]

                          Missing Values  Missing Percentage (%)
Teacher_Quality                       78                    1.18
Parental_Education_Level              90                    1.36
Distance_from_Home                    67                    1.01

In [10]:
# Cell 8 - Handle Missing Values

categorical_missing_columns = [
    "Teacher_Quality",
    "Parental_Education_Level",
    "Distance_from_Home"
]

for col in categorical_missing_columns:
    if col in df.columns:
        mode_value = df[col].mode()[0]
        df[col] = df[col].fillna(mode_value)
        print(f"Filled missing values in {col} with mode: {mode_value}")
    else:
        print(f"Column not found: {col}")

Filled missing values in Teacher_Quality with mode: Medium
Filled missing values in Parental_Education_Level with mode: High School
Filled missing values in Distance_from_Home with mode: Near

In [11]:
# Cell 9 - Confirm Missing Values Fixed

df.isnull().sum().sort_values(ascending=False)

Hours_Studied                 0
Attendance                    0
Parental_Involvement          0
Access_to_Resources           0
Extracurricular_Activities    0
Sleep_Hours                   0
Previous_Scores               0
Motivation_Level              0
Internet_Access               0
Tutoring_Sessions             0
Family_Income                 0
Teacher_Quality               0
School_Type                   0
Peer_Influence                0
Physical_Activity             0
Learning_Disabilities         0
Parental_Education_Level      0
Distance_from_Home            0
Gender                        0
Exam_Score                    0
dtype: int64

In [12]:
# Cell 10 - Check Duplicate Rows

duplicate_count = df.duplicated().sum()

print(f"Number of duplicate rows: {duplicate_count}")

Number of duplicate rows: 0

In [13]:
# Cell 11 - Remove Duplicates If Found

if duplicate_count > 0:
    df = df.drop_duplicates()
    print("Duplicate rows removed.")
else:
    print("No duplicate rows found.")

print("Dataset shape after duplicate check:", df.shape)

No duplicate rows found.
Dataset shape after duplicate check: (6607, 20)

In [15]:
# Cell 12 - Numerical Summary

df.describe().T

                    count       mean        std   min   25%   50%   75%    max
Hours_Studied      6607.0  19.975329   5.990594   1.0  16.0  20.0  24.0   44.0
Attendance         6607.0  79.977448  11.547475  60.0  70.0  80.0  90.0  100.0
Sleep_Hours        6607.0   7.029060   1.468120   4.0   6.0   7.0   8.0   10.0
Previous_Scores    6607.0  75.070531  14.399784  50.0  63.0  75.0  88.0  100.0
Tutoring_Sessions  6607.0   1.493719   1.230570   0.0   1.0   1.0   2.0    8.0
Physical_Activity  6607.0   2.967610   1.031231   0.0   2.0   3.0   4.0    6.0
Exam_Score         6607.0  67.235659   3.890456  55.0  65.0  67.0  69.0  101.0

In [16]:
# Cell 13 - Check Invalid Exam Score Values

print("Minimum Exam Score:", df["Exam_Score"].min())
print("Maximum Exam Score:", df["Exam_Score"].max())

invalid_exam_scores = df[(df["Exam_Score"] < 0) | (df["Exam_Score"] > 100)]

print("Number of invalid Exam_Score values:", len(invalid_exam_scores))
invalid_exam_scores

Minimum Exam Score: 55
Maximum Exam Score: 101
Number of invalid Exam_Score values: 1

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
1525,27,98,Low,Medium,Yes,6,93,Low,No,5,High,High,Public,Positive,3,No,High School,Moderate,Female,101

In [17]:
# Cell 14 - Correct Invalid Exam Score

df["Exam_Score"] = df["Exam_Score"].clip(lower=0, upper=100)

print("Minimum Exam Score after correction:", df["Exam_Score"].min())
print("Maximum Exam Score after correction:", df["Exam_Score"].max())

Minimum Exam Score after correction: 55
Maximum Exam Score after correction: 100

In [18]:
# Cell 15 - Create Target Variable

df["Performance_Label"] = np.where(df["Exam_Score"] >= 60, "Pass", "Fail")

df["Pass_Fail"] = np.where(df["Exam_Score"] >= 60, 1, 0)

df[["Exam_Score", "Performance_Label", "Pass_Fail"]].head(10)

   Exam_Score Performance_Label  Pass_Fail
0          67              Pass          1
1          61              Pass          1
2          74              Pass          1
3          71              Pass          1
4          70              Pass          1
5          71              Pass          1
6          67              Pass          1
7          66              Pass          1
8          69              Pass          1
9          72              Pass          1

In [19]:
# Cell 16 - Check Target Distribution

target_counts = df["Performance_Label"].value_counts()
target_percentage = df["Performance_Label"].value_counts(normalize=True) * 100

target_distribution = pd.DataFrame({
    "Count": target_counts,
    "Percentage (%)": target_percentage.round(2)
})

target_distribution

                   Count  Percentage (%)
Performance_Label
Pass                6539           98.97
Fail                  68            1.03

In [20]:
# Cell 17 - Final Validation Checks

required_columns = [
    "Exam_Score",
    "Performance_Label",
    "Pass_Fail"
]

print("Final Validation Checks")
print("-" * 50)

for col in required_columns:
    assert col in df.columns, f"Missing required column: {col}"
    print(f"{col}: Found")

missing_total = df.isnull().sum().sum()
assert missing_total == 0, "There are still missing values in the dataset."
print("Missing values: 0")

duplicate_total = df.duplicated().sum()
assert duplicate_total == 0, "There are duplicate rows in the dataset."
print("Duplicate rows: 0")

assert df["Exam_Score"].between(0, 100).all(), "Exam_Score contains invalid values."
print("Exam_Score range: Valid between 0 and 100")

assert set(df["Performance_Label"].unique()).issubset({"Pass", "Fail"}), "Invalid labels found."
assert set(df["Pass_Fail"].unique()).issubset({0, 1}), "Invalid numeric target values found."
print("Target labels: Valid")

print("\nAll final validation checks passed successfully.")

Final Validation Checks
--------------------------------------------------
Exam_Score: Found
Performance_Label: Found
Pass_Fail: Found
Missing values: 0
Duplicate rows: 0
Exam_Score range: Valid between 0 and 100
Target labels: Valid

All final validation checks passed successfully.

In [21]:
# Cell 18 - Check Final Dataset

print("Final Dataset Shape:")
print(f"Rows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")

df.head()

Final Dataset Shape:
Rows: 6607
Columns: 22

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,...,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score,Performance_Label,Pass_Fail
0,23,84,Low,High,No,7,73,Low,Yes,0,...,Public,Positive,3,No,High School,Near,Male,67,Pass,1
1,19,64,Low,Medium,No,8,59,Low,Yes,2,...,Public,Negative,4,No,College,Moderate,Female,61,Pass,1
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,...,Public,Neutral,4,No,Postgraduate,Near,Male,74,Pass,1
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,...,Public,Negative,4,No,High School,Moderate,Male,71,Pass,1
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,...,Public,Neutral,4,No,College,Near,Female,70,Pass,1

In [22]:
# Cell 19 - Save Cleaned Dataset

PROCESSED_DATA_PATH.parent.mkdir(parents=True, exist_ok=True)

df.to_csv(PROCESSED_DATA_PATH, index=False)

print("Cleaned dataset saved successfully.")
print("Saved to:", PROCESSED_DATA_PATH)

Cleaned dataset saved successfully.
Saved to: ..\data\processed\StudentPerformanceFactors_cleaned.csv

In [23]:
# Cell 20 - Save Data Cleaning Summary

cleaning_summary_path = TABLES_DIR / "data_cleaning_summary.txt"

cleaning_summary = f"""
Data Cleaning Summary

Dataset: StudentPerformanceFactors.csv

Final dataset shape:
Rows: {df.shape[0]}
Columns: {df.shape[1]}

Cleaning steps completed:
1. Loaded the raw dataset.
2. Checked dataset structure and data types.
3. Identified and handled missing categorical values.
4. Checked duplicate records.
5. Corrected invalid Exam_Score values using clipping between 0 and 100.
6. Created Performance_Label:
   - Pass if Exam_Score >= 60
   - Fail if Exam_Score < 60
7. Created Pass_Fail:
   - Pass = 1
   - Fail = 0
8. Saved the cleaned dataset.

Final checks:
Missing values: {df.isnull().sum().sum()}
Duplicate rows: {df.duplicated().sum()}
Minimum Exam_Score: {df["Exam_Score"].min()}
Maximum Exam_Score: {df["Exam_Score"].max()}

Target distribution:
{df["Performance_Label"].value_counts().to_string()}
"""

with open(cleaning_summary_path, "w", encoding="utf-8") as file:
    file.write(cleaning_summary)

print("Data cleaning summary saved successfully.")
print("Saved to:", cleaning_summary_path)

Data cleaning summary saved successfully.
Saved to: ..\outputs\tables\data_cleaning_summary.txt

In [24]:
# Cell 21 - Reload and Verify Saved File

df_cleaned = pd.read_csv(PROCESSED_DATA_PATH)

print("Reloaded cleaned dataset shape:", df_cleaned.shape)
df_cleaned.head()

Reloaded cleaned dataset shape: (6607, 22)

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,...,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score,Performance_Label,Pass_Fail
0,23,84,Low,High,No,7,73,Low,Yes,0,...,Public,Positive,3,No,High School,Near,Male,67,Pass,1
1,19,64,Low,Medium,No,8,59,Low,Yes,2,...,Public,Negative,4,No,College,Moderate,Female,61,Pass,1
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,...,Public,Neutral,4,No,Postgraduate,Near,Male,74,Pass,1
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,...,Public,Negative,4,No,High School,Moderate,Male,71,Pass,1
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,...,Public,Neutral,4,No,College,Near,Female,70,Pass,1

In [25]:
# Cell 22 - Final Cleaning Summary

print("DATA CLEANING SUMMARY")
print("-" * 40)
print(f"Final dataset rows: {df_cleaned.shape[0]}")
print(f"Final dataset columns: {df_cleaned.shape[1]}")
print("Missing values after cleaning:", df_cleaned.isnull().sum().sum())
print("Duplicate rows after cleaning:", df_cleaned.duplicated().sum())
print("Minimum Exam Score:", df_cleaned["Exam_Score"].min())
print("Maximum Exam Score:", df_cleaned["Exam_Score"].max())
print("\nTarget Distribution:")
print(df_cleaned["Performance_Label"].value_counts())

DATA CLEANING SUMMARY
----------------------------------------
Final dataset rows: 6607
Final dataset columns: 22
Missing values after cleaning: 0
Duplicate rows after cleaning: 0
Minimum Exam Score: 55
Maximum Exam Score: 100

Target Distribution:
Performance_Label
Pass    6539
Fail      68
Name: count, dtype: int64

# Cell 23 - Markdown
"""
## Cleaning Summary

The dataset was successfully cleaned and prepared for machine learning.

Completed steps:
1. Loaded the raw dataset.
2. Checked dataset size, column names, and data types.
3. Identified and filled missing categorical values using mode.
4. Checked duplicate records.
5. Corrected invalid exam score values by clipping scores to 0–100.
6. Created two target columns:
   - Performance_Label: Pass or Fail
   - Pass_Fail: 1 for Pass and 0 for Fail
7. Validated the cleaned dataset.
8. Saved the cleaned dataset and cleaning summary.

The cleaned dataset is now ready for EDA and modeling.
"""